=== blaiyz/neosoft-zebar/static/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "AttachmentDirection": {
      "enum": ["bottom", "floating", "top"],
      "type": "string"
    },
    "BackgroundEffect": {
      "enum": ["acrylic", "blur", "inherit", "mica"],
      "type": "string"
    },
    "GradientDirection": {
      "enum": ["bottom", "disabled", "solid", "top"],
      "type": "string"
    },
    "ProvidersConfig": {
      "properties": {
        "enableErrorLogging": {
          "description": "Whether to enable error logging for providers.",
          "type": "boolean"
        },
        "refreshIntervals": {
          "description": "The refresh intervals for some providers.",
          "properties": {
            "battery": {
              "type": "number"
            },
            "cpu": {
              "type": "number"
            },
            "memory": {
              "type": "number"
            },
            "network": {
              "type": "number"
            },
            "weather": {
              "type": "number"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "TaskbarIntegration": {
      "properties": {
        "enabled": {
          "description": "Whether to integrate with the windows taskbar.",
          "type": "boolean"
        },
        "extraIcons": {
          "description": "The number of additional icons that appear in the taskbar (like windows logo or search).",
          "type": "number"
        },
        "primaryMonitorSelection": {
          "$ref": "#/definitions/WindowSelection",
          "description": "Which windows to include in the number of taskbar icons."
        },
        "secondaryMonitorSelection": {
          "$ref": "#/definitions/WindowSelection"
        }
      },
      "type": "object"
    },
    "WindowSelection": {
      "enum": ["all", "monitor", "workspace"],
      "type": "string"
    }
  },
  "properties": {
    "attachSides": {
      "description": "Whether to attach the left and right sides of the widgets or to use smooth corners.\n\nTo see the full corners, you must have some margin (`--bar-margin-x` in `config.css`)",
      "type": "boolean"
    },
    "backgroundEffect": {
      "$ref": "#/definitions/BackgroundEffect",
      "description": "The background effect to use for the widget.\n\nNOTE: In order to use anything other than inherit, you must recompile zebar with an extra permission. More details in the README.\n\n`inherit`- Don't change the effect, and use the one defined in zpack.json (probably transparent).\n`acrylic`- Use an acrylic background effect. Windows 10, 11.\n`blur`- Use a blur background effect. Windows 10, 11.\n`mica`- Use a mica background effect. Windows 11 only."
    },
    "clickThroughByDefault": {
      "description": "Enable click-through by default.",
      "type": "boolean"
    },
    "direction": {
      "$ref": "#/definitions/AttachmentDirection",
      "description": "The visual direction of the widget.\n\n`top`- The top of the widget has inverted corner radius, and the bottom has normal corner radius.\n\n`bottom`- The bottom of the widget has inverted corner radius, and the top has normal corner radius.\n\n`floating`- All corners of the widget have normal corner radius."
    },
    "enableAutoTiling": {
      "description": "Whether to enable built-in automatic tiling of windows.",
      "type": "boolean"
    },
    "extendVolumeSliderByDefault": {
      "description": "Enable volume slider by default.",
      "type": "boolean"
    },
    "gradient": {
      "$ref": "#/definitions/GradientDirection",
      "description": "The direction of the background gradient.\n\n`top`- From top to transparent bottom.\n\n`bottom`- From bottom to transparent top.\n\n`solid`- Solid color background.\n\n`disabled`- Background color is disabled."
    },
    "providersConfig": {
      "$ref": "#/definitions/ProvidersConfig",
      "description": "Options for the providers, including refresh intervals and error logging."
    },
    "showBatterySection": {
      "type": "boolean"
    },
    "showCpuSection": {
      "type": "boolean"
    },
    "showFullDateByDefault": {
      "description": "Whether to show the full date by default instead of just the time.\n\n(This can be toggled in the UI by clicking the date/time)",
      "type": "boolean"
    },
    "showHeartButton": {
      "type": "boolean"
    },
    "showMemorySection": {
      "type": "boolean"
    },
    "showNetworkSection": {
      "enum": [false, "interface", "statistics", true]
    },
    "showSeconds": {
      "type": "boolean"
    },
    "showShutdownButton": {
      "type": "boolean"
    },
    "showWeatherSection": {
      "type": "boolean"
    },
    "taskbarIntegration": {
      "$ref": "#/definitions/TaskbarIntegration",
      "description": "Whether to integrate with the windows taskbar.\n\nRight now, this feature only adds an area at the center of the widget that contains the window icons. Please see README for more information."
    },
    "transitionDuration": {
      "description": "The duration of transitions in milliseconds.",
      "type": "number"
    },
    "use24hClock": {
      "enum": ["auto", false, true]
    },
    "useCelsiusByDefault": {
      "type": "boolean"
    },
    "useThinnerWorkspaceButtons": {
      "type": "boolean"
    }
  },
  "type": "object"
}

=== blaiyz/neosoft-zebar/static/config.json
{
  "$schema": "./schema.json",
  "direction": "top",
  "gradient": "top",
  "attachSides": true,
  "taskbarIntegration": {
    "enabled": false,
    "extraIcons": 0,
    "primaryMonitorSelection": "all",
    "secondaryMonitorSelection": "monitor"
  },
  "transitionDuration": 400,
  "providersConfig": {
    "refreshIntervals": {
      "cpu": 2000,
      "memory": 5000,
      "battery": 60000,
      "weather": 900000,
      "network": 2000
    },
    "enableErrorLogging": false
  },
  "backgroundEffect": "inherit",
  "enableAutoTiling": true,
  "clickThroughByDefault": false,
  "showShutdownButton": true,
  "showHeartButton": true,
  "showCpuSection": true,
  "showMemorySection": true,
  "showBatterySection": true,
  "showNetworkSection": true,
  "extendVolumeSliderByDefault": false,
  "showWeatherSection": true,
  "useCelsiusByDefault": true,
  "showFullDateByDefault": false,
  "use24hClock": "auto",
  "showSeconds": false,
  "useThinnerWorkspaceButtons": false
}
